Hi 👋, I'm @MisTerApps
full stack developer from Turkey
ferixinder

ferixinder

Connect with me:
ferixinder 15162153 ferixinder ferixinder m4QQk2HKbE

Languages and Tools:
bootstrap chartjs csharp css3 electron figma firebase go heroku html5 javascript kotlin linux mariadb mongodb mysql nodejs photoshop php react reactnative redis

ferixinder

 ferixinder
